
// Catálogo de códigos de error expuestos por la API.

module.exports = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  EMAIL_SERVICE_UNAVAILABLE: 'EMAIL_SERVICE_UNAVAILABLE',
  FILE_TYPE_UNSUPPORTED: 'FILE_TYPE_UNSUPPORTED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ACTIVE_COMMUNITY_INVALID: 'ACTIVE_COMMUNITY_INVALID',
  ACTIVE_COMMUNITY_NOT_FOUND: 'ACTIVE_COMMUNITY_NOT_FOUND',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  ACCOUNT_DELETION_EMAIL_MISMATCH: 'ACCOUNT_DELETION_EMAIL_MISMATCH',
  CONFIRMATION_TEXT_MISMATCH: 'CONFIRMATION_TEXT_MISMATCH',
  ACCOUNT_DELETION_FAILED: 'ACCOUNT_DELETION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS'
};
